### ISSUE TITLE
Firefox freeze on linkedin website !

### ISSUE THREAD

**Issue by amriunix** [AliasIO/Wappalyzer#2061]
firefox 58.0.1 + Wappalyzer 5.4.6 on Ubuntu 16.04.3 LTS

**Comment by gadcam** [comment]
I can confirm on windows that something strange is going on with Wappalyzer. One core is monopolized for several seconds.
One call to analyzeHtml is going crazy.
Maybe this commit fix it 28a93d5.

**Comment by ssaarinen** [comment]
This happens also when visiting aws console on win 10, ff 58.0.1 & wappalyzer 5.4.6. CPU 100% on 1 core.

**Comment by dmangin** [comment]
Hi same thing here (Max OS X 10.13.3, FF 59) on several websites (Atlassian, ...)

**Comment by SkySymbol** [comment]
Same on airbnb, the freeze happens after requests to a1.muscache.com. Running firefox nightly build ID 20180207100355 on Arch Linux with wappalyzer 5.4.6.

**Comment by axllent** [comment]
Confirmed, I'm experiencing the same on Ubuntu 16.04 with both Linkedin and Jira (Atlassian) - Firefox (nightly) will hang for about 30-40 seconds at 100% cpu before it comes back to life again. Disabling Wappalyzer was the only solution :-(

**Comment by Conorbro** [comment]
Same issue with both Linkedin and Facebook on macOS Sierra 10.13.3 Firefox 58.0.1 (64-bit)

**Comment by AliasIO** [comment]
Fixed in v5.4.7, going out today. Thanks, all.

**Comment by axllent** [comment]
Jira still has a problem with this addon unfortunately. Linkedin & Facebook seem to be fixed.

**Comment by gadcam** [comment]
Can you give us an example URL to test against it ?

**Comment by axllent** [comment]
Unfortunately my Jira access is company-login-only so I cannot give you access to that, however it happens while viewing any of the boards (ie: "Kanban boards") when cards (issues) are loading in. Assuming you have access to any Jira project then https://stsconsulting.atlassian.net/secure/RapidBoard.jspa should show you what I mean.

Initially the page loads fine, but when the issues (job cards) are loading in via ajax (probably 10-15 in total, not 1000s) the browser locks up for a while (less than before 5.4.7, but still 10-20 seconds). It is definitely related to Wappalyzer as disabling the addon solved the problem 100%.

**Comment by axllent** [comment]
Actually, I still get this on Linkedin too. Just viewing anything like https://www.linkedin.com/feed/

**Comment by gadcam** [comment]
@amriunix, @ssaarinen, @dmangin, @SkySymbol, @Conorbro can you still reproduce this bug with Wappalyzer 5.4.11 ?
I pushed a fix for a lookalike issue which was merged in 27e1fa1.
If it did not fix I need a *reproducible* way to debug it : so at least a complete URL and maybe some preconditions.

**Comment by SkySymbol** [comment]
This fixes the issue for me. Thank you for your work :-)
