### ISSUE TITLE
Wappalyzer - Updating to latest version breaks the extension.

### ISSUE THREAD

**Issue by KSword007** [AliasIO/wappalyzer#3159]
Which platform does the bug apply to?
Google Chrome Store Extension (Installed to the new Microsoft Edge via Chrome Store)
Seems to affect all websites.

After updating to the latest version of Wappalyzer (as of June 10th, 2020), the extension does not recognize web pages or provide any contextual information. I have reinstalled the program to no effect.

- Install the newest version or update from an existing install.
- The error shows itself.

Edit #1 - removed accidental image upload.
Edit #2 - fixed minor spelling error.
Edit #3 - corrected time/date error (from 6th of June to 10th of June)

**Comment by KSword007** [comment]
UPDATE - Enabling then disabling the extension will cause it to briefly work for only ONE website. The bug will then take hold and Wappalyzer will not work.

**Comment by connorwhitman** [comment]
Here's the console log of the error. The main error is `QUOTA_BYTES quota exceeded`.

`wappalyzer | driver | Connected to adparser
driver.js:80 wappalyzer | driver | {port: "adparser", func: "onAd", args: Array(1)}args: [{…}]0: assets: []doc: {url: "https://github.com/2957839219", isHP: false, referrer: "https://github.com/5743686810?3222539893", rand: 547382559317, startTime: 1591829058854}event: "unload"mrev: "15a9f21-d"msgNum: 1pageFoc: truepageTags: []pageVis: "visible"timestamp: 1591829139817timing: {connectStart: 1591829057729, navigationStart: 1591829057728, loadEventEnd: 1591829059507, domLoading: 1591829058769, secureConnectionStart: 0, …}version: "3"video_assets: []__proto__: Objectlength: 1__proto__: Array(0)func: "onAd"port: "adparser"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
driver.js:80 wappalyzer | driver | Connected to adparser
driver.js:80 wappalyzer | driver | Error: QUOTA_BYTES quota exceeded
    at setOption (utils.js:44)
    at async Object.onDetect (driver.js:260)
    at async onWebRequestComplete (driver.js:186)
log @ driver.js:80
error @ driver.js:88
onWebRequestComplete @ driver.js:193
async function (async)
onWebRequestComplete @ driver.js:169
driver.js:80 wappalyzer | driver | Connected to adparser
driver.js:80 wappalyzer | driver | {port: "adparser", func: "onAd", args: Array(1)}args: [{…}]func: "onAd"port: "adparser"__proto__: Object
driver.js:80 wappalyzer | driver | Connected to content.js
driver.js:80 wappalyzer | driver | {port: "content.js", func: "onContentLoad", args: Array(3)}args: (3) ["https://github.com/AliasIO/wappalyzer/issues/3159", {…}, "en"]0: "https://github.com/AliasIO/wappalyzer/issues/3159"1: {html: "<!DOCTYPE html><html xmlns="http://www.w3.org/1999…city: 0.9;cursor: pointer;"></span></body></html>", scripts: Array(4), meta: Array(65), cookies: Array(11)}2: "en"length: 3__proto__: Array(0)func: "onContentLoad"port: "content.js"__proto__: Object
driver.js:80 wappalyzer | driver | {port: "content.js", func: "getTechnologies", args: undefined}args: undefinedfunc: "getTechnologies"port: "content.js"__proto__: Object
driver.js:80 wappalyzer | driver | {port: "content.js", func: "analyzeJs", args: Array(2)}args: (2) ["https://github.com/AliasIO/wappalyzer/issues/3159", Array(2)]func: "analyzeJs"port: "content.js"__proto__: Object
driver.js:80 wappalyzer | driver | Error: QUOTA_BYTES quota exceeded
    at setOption (utils.js:44)
    at async Object.onDetect (driver.js:260)
    at async Object.onContentLoad (driver.js:206)
    at async chrome-extension:/gppongmhjkpfnbhagpmjfkannfbllamg/js/driver.js:157
log @ driver.js:80
error @ driver.js:88
onContentLoad @ driver.js:208
async function (async)
onContentLoad @ driver.js:202
(anonymous) @ driver.js:157`

**Comment by AliasIO** [comment]
Thanks, I just pushed a fix for this. Look out for v6.0.5.

**Comment by shanerobinson** [comment]
Working perfectly now in v6.0.6 👏🏼👏🏼👏🏼

**Comment by Silentxknight** [comment]
#showing less info

I tried on YouTube previously it used to show "Hammer.js" ,"Polymer" &  "Google Font Api"
now only shows "Google Font Api"
And no working on Amazon, showing less info

**Comment by willyarisky** [comment]
Please update for edge on microsoft ext store. I didn't get an update to fix this issue

**Comment by marcajhouben** [comment]
Updated chrome extension still not working, only for several URLs - same with other people using the extension.

**Comment by wxh06** [comment]
[Wappalyzer 6.0.7](https://github.com/AliasIO/wappalyzer/releases/tag/v6.0.7) works!
But without translation ... it shows English only
![屏幕快照 2020-06-11 下午6 35 53](https://user-images.githubusercontent.com/29367025/84375659-7fb24600-ac12-11ea-8600-20291eb317a2.png)
This problem was also introduced in [Wappalyzer 6.0.4](https://github.com/AliasIO/wappalyzer/releases/tag/v6.0.4)

**Comment by Liakoni** [comment]
In Firefox 77.0.1 wappalyzer 6.0.7 doen't work.

**Comment by kyletaylored** [comment]
It looks like it breaks on sites where a detected technology has an implied confidence score, like the regex parsing isn't happening and that's throwing errors. I've only seen this break on sites where the implied confidence score exists.

![Implied confidence is breaking extension](https://user-images.githubusercontent.com/1759794/84406350-05140700-abcf-11ea-80a1-097fbc795326.png)

**Comment by somepaulo** [comment]
> In Firefox 77.0.1 wappalyzer 6.0.7 doen't work.

Same here. On Arch 64 bit with Linux 5.7.2

**Comment by AliasIO** [comment]
Fixed in 1a605c417135ad22854e88297f7fe47ce430c5c1. Thanks for the clue @kyletaylored.
